### ISSUE TITLE
Mod doesn't work?

### ISSUE THREAD

**Issue by HCSarise** [dmillerw/Insomnia#1]
I sleep in a vanilla minecraft bed and it passes the night as per usual. Does it need to be installed directly into the jar instead of the mods folder?

**Comment by dmillerw** [comment]
That's really weird. It should work just fine... works in testing.

**Comment by HCSarise** [comment]
I'll try it just by itself, maybe there's a conflict somewhere with one of my other mods.

**Comment by HCSarise** [comment]
I tried it with just the latest version of forge and this mod, and it doesn't work. I'm doing this on single player, is that perhaps why it's not working?

**Comment by dmillerw** [comment]
Oh, fixed
